### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [techmovie/bbc-global-news-transcripts#1]
HELLO MAN...CONGRATULATIONS FOR YOUR AMAZING PROJECT!!!BUT COULD YOU PLEASE TELL ME STEP BY STEP WHAT I HAVE TO DO FOR USE YOUR AMAZING PROJECT?I AM NEW ON THIS AND I DONT KNOW!!!

**Comment by xheiop** [comment]
What do you need to do with this project? I think REAMDE.md is clear enough.

**Comment by KENPOKASMMA1982** [comment]
I MEAN MY FRIEND WHAT I HAVE TO RUN ON CMD?
